version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: checkpoint
      POSTGRES_PASSWORD: checkpoint
      POSTGRES_DB: checkpoint_dev
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
